default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  username: root
  password: 

development:
  <<: *default
  database: cragbrag_development

test:
  <<: *default
  database: cragbrag_test